name: REDACTED
color: '#6c32c3'
datatable:
  datatables:
    main:
      database:
        resource_path: f/eval/pg_resource
        resource_type: postgresql
error_handler: null
operator_settings:
  assets: true
  audit_logs: true
  folders: true
  groups: true
  resources: true
  runs: true
  schedules: true
  triggers: true
  variables: true
  workers: true
slack_oauth_client_id: null
slack_oauth_client_secret: null
success_handler: null
